README: Update instructions
foundriesio/mirror-action pull request #4
Opened 2021-09-07 15:47 UTC by munoz0raul

README: Update instructions
    
    - Changed to actions/checkout@v2
    - Suggested PUSH_ALL_REFS = "true" defualt
    - Added GITHUB_REF = "<branch>" on cases PUSH_ALL_REFS = "false"

2021-09-07 16:04 UTC, doanac approved these changes

2021-09-13 21:54 UTC, mike-scott requested changes

2021-09-13 21:54 UTC, mike-scott commented on README.md
> +          PUSH_ALL_REFS: "true"
Let's not do this by default please.

2021-09-13 21:54 UTC, mike-scott commented on README.md
> +**NOTE:** by default, all branches are pushed. If you want to avoid
Please change this to the reverse.

2021-09-13 22:33 UTC, mike-scott approved these changes
LGTM

2021-09-13 22:34 UTC, merged